# Generated by Django 2.2.2 on 2019-06-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LostItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(default='empty', max_length=120)),
                ('doc_name', models.CharField(default='empty', max_length=120)),
                ('real_doc_id', models.CharField(default='empty', max_length=120)),
                ('fake_doc_id', models.CharField(default='empty', max_length=120)),
                ('status', models.CharField(default='Not Found', max_length=120)),
                ('img_path', models.FileField(upload_to='')),
                ('desc', models.CharField(default='empty', max_length=300)),
                ('found_person_name', models.CharField(default='empty', max_length=120)),
                ('found_person_phone', models.CharField(default='empty', max_length=120)),
            ],
        ),
    ]
