# Generated by Django 2.2.2 on 2019-06-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lostitems',
            name='desc',
        ),
        migrations.AddField(
            model_name='lostitems',
            name='found_dec',
            field=models.TextField(default='empty'),
        ),
        migrations.AddField(
            model_name='lostitems',
            name='lost_desc',
            field=models.TextField(default='empty'),
        ),
        migrations.AlterField(
            model_name='lostitems',
            name='img_path',
            field=models.ImageField(upload_to='media'),
        ),
    ]
