# Generated by Django 2.2.2 on 2019-06-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190604_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitems',
            name='img_path',
            field=models.CharField(default='Not found', max_length=100),
        ),
    ]
