# Generated by Django 2.2.2 on 2019-06-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190604_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitems',
            name='found_dec',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lostitems',
            name='lost_desc',
            field=models.TextField(),
        ),
    ]
