# Generated by Django 2.2.2 on 2019-06-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190604_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lostitems',
            old_name='found_dec',
            new_name='found_desc',
        ),
        migrations.AddField(
            model_name='lostitems',
            name='owner_phone',
            field=models.CharField(default='empty', max_length=20),
        ),
    ]
