# Generated by Django 2.2.2 on 2019-06-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190604_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.FileField(upload_to='image/%Y/%m/%d')),
                ('found_desc', models.TextField()),
                ('found_person_name', models.CharField(default='empty', max_length=120)),
                ('found_person_phone', models.CharField(default='empty', max_length=120)),
            ],
        ),
    ]
