# Generated by Django 2.2.2 on 2019-06-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190609_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitems',
            name='found_desc',
            field=models.TextField(default='Empty', null=True),
        ),
        migrations.AlterField(
            model_name='lostitems',
            name='lost_desc',
            field=models.TextField(default='Empty', null=True),
        ),
    ]
