# Generated by Django 2.2.2 on 2019-06-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190609_0611'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncommingMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(default='empty', max_length=120)),
                ('subject', models.CharField(default='empty', max_length=120)),
                ('email', models.CharField(default='empty', max_length=120)),
                ('message', models.TextField(null=True)),
                ('status', models.CharField(default='Responded', max_length=40)),
            ],
        ),
    ]
