# Generated by Django 2.2.2 on 2019-06-10 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_incommingmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IncommingMessage',
            new_name='IncomingMessage',
        ),
    ]
