# Generated by Django 2.2.2 on 2019-06-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='empty', max_length=120)),
                ('last_name', models.CharField(default='empty', max_length=120)),
                ('phone', models.CharField(default='empty', max_length=120)),
                ('password', models.CharField(default='empty', max_length=240)),
            ],
        ),
    ]
